"""Fleet list -> per-node bundles for REAL hardware: one OpenWrt router setup
script per node, plus the host side (Jetson / operator laptop): static mesh
address, zenohd + node env, UDP Status endpoint, chrony.

    python3 -m commsim.hw.deploy commsim/configs/base.yaml commsim/configs/hw_lab.yaml \\
        --mesh-key-file ~/.config/sortbots/mesh.key --out commsim/results/hw
    python3 -m commsim.hw.deploy ... --new-key     # create the key file first

Same fleet list, timer check and isolation check as the emulation
(core/fleet.py, core/timers.py), so the hardware runs the configuration the
simulation measured, not a hand-copied one. Walkthrough: commsim/hw/README.md.

Each router: 802.11s mesh point per band (mesh_fwding 0, SAE), batman-adv IV
over them as bat0, bat0 bridged with the LAN port the host plugs into.
L2 bridge, so the host's fleet IP is reachable over the mesh with no routing
on the router and batman's translation table carries the host's MAC.

The bundle contains the mesh key. The repo is public: --out must be outside
it or under a gitignored path, and the files are written owner-only.
"""
from __future__ import annotations

import argparse
import ipaddress
import json
import os
import secrets
import shlex
import subprocess
import sys
from pathlib import Path

from commsim.core import fleet as F
from commsim.core.timers import check as check_timers

REPO = Path(__file__).resolve().parents[2]
# OpenWrt band names; channel from the radio: section of the config.
OPENWRT_BAND = {"g24": "2g", "g5": "5g"}
# 802.11g/a OFDM rates only: no 1/2/5.5/11 Mb/s 802.11b rates. In the first
# n=10 emulation minstrel spent ~40% of frames at 1 and 5.5 Mb/s (sim_log
# step 8), the single biggest airtime cost found.
OFDM_RATES = "6 9 12 18 24 36 48 54"


def router_ip(node: F.Node, cfg: dict) -> str:
    """Router management address, counted down from the top of the subnet so
    it can't collide with host addresses counted up from the bottom."""
    net = ipaddress.ip_network(cfg["fleet"]["subnet"])
    return str(net.broadcast_address - 1 - node.robot_id)


def check_addresses(fleet: list[F.Node], cfg: dict) -> None:
    hosts = {ipaddress.ip_address(n.ip) for n in fleet}
    routers = {ipaddress.ip_address(router_ip(n, cfg)) for n in fleet}
    if hosts & routers or min(routers) <= max(hosts):
        raise ValueError(f"subnet {cfg['fleet']['subnet']} too small: host and router addresses overlap")


def router_script(node: F.Node, fleet: list[F.Node], cfg: dict, key: str, sources: str) -> str:
    """POSIX sh (OpenWrt ash) run once on a freshly reset router. Pure uci:
    radios are found by band, the LAN bridge by name, so the same script works
    on any router model that meets commsim/hw/README.md's minimum."""
    net = ipaddress.ip_network(cfg["fleet"]["subnet"])
    hw, radio, bat = cfg["hardware"], cfg["radio"], cfg["batman"]
    q = shlex.quote
    bands = cfg["fleet"].get("bands", ["g24"])
    lines = [
        "#!/bin/sh",
        f"# SortBots mesh router for {node.name} — generated by commsim/hw/deploy.py",
        f"# from {sources}. Regenerate rather than edit. Contains the mesh key.",
        "#",
        "#   scp -O router-setup.sh root@192.168.1.1:/tmp/ && ssh root@192.168.1.1 sh /tmp/router-setup.sh",
        "#",
        f"# Afterwards the router answers on {router_ip(node, cfg)} (from a host on the mesh",
        "# subnet), no longer on 192.168.1.1.",
        "set -e",
        'fail() { echo "router-setup: $*" >&2; exit 1; }',
        "",
        "# --- preconditions: packages (README step 2) -----------------------------",
        "command -v batctl >/dev/null || fail 'batctl missing (install kmod-batman-adv batctl-default)'",
        "[ -d /sys/module/batman_adv ] || modprobe batman-adv 2>/dev/null || fail 'kmod-batman-adv missing'",
        "# Mesh + SAE need a full wpad; the default wpad-basic-* builds lack mesh.",
        "wpa_supplicant -vmesh >/dev/null 2>&1 || fail 'wpad without mesh support (install wpad-mesh-mbedtls)'",
        "wpa_supplicant -vsae >/dev/null 2>&1 || fail 'wpad without SAE support (install wpad-mesh-mbedtls)'",
        "# `master` on batadv_hardif and DSA bridge devices are OpenWrt 22.03+.",
        "uci -q show network | grep -q \"\\.name='br-lan'\" || fail 'no br-lan bridge device: OpenWrt 22.03 or newer needed'",
        "",
        "radio_for() {  # $1 = 2g|5g -> radio section name",
        "  for r in $(uci -q show wireless | sed -n 's/^wireless\\.\\([^.=]*\\)=wifi-device$/\\1/p'); do",
        "    b=$(uci -q get wireless.$r.band || true)",
        "    if [ -z \"$b\" ]; then  # pre-21.02 configs say hwmode instead",
        "      case \"$(uci -q get wireless.$r.hwmode || true)\" in 11a) b=5g ;; 11b|11g|11n) b=2g ;; esac",
        "    fi",
        "    [ \"$b\" = \"$1\" ] && { echo \"$r\"; return 0; }",
        "  done",
        "  return 1",
        "}",
        "",
        f"MESH_KEY={q(key)}",
        "",
        "# --- radios: 802.11s mesh point per band ----------------------------------",
        "# Drop the stock AP interfaces: an AP on a robot is an open door onto bat0.",
        "while uci -q delete 'wireless.@wifi-iface[0]'; do :; done",
    ]
    for b in bands:
        rb = radio[b]
        iface = f"mesh_{b}"
        lines += [
            "",
            f"r=$(radio_for {OPENWRT_BAND[b]}) || fail 'no {OPENWRT_BAND[b]} radio on this router'",
            f"uci set wireless.$r.channel={q(str(rb['channel']))}",
            f"uci set wireless.$r.htmode={q(hw.get('htmode', 'HT20'))}",
            f"uci set wireless.$r.country={q(hw['country'])}",
            "uci set wireless.$r.cell_density=0",
            "uci set wireless.$r.disabled=0",
            f"uci set wireless.{iface}=wifi-iface",
            f"uci set wireless.{iface}.device=$r",
            f"uci set wireless.{iface}.ifname={q(iface.replace('_', '-'))}",
            f"uci set wireless.{iface}.mode=mesh",
            f"uci set wireless.{iface}.mesh_id={q(radio['mesh_id'])}",
            f"uci set wireless.{iface}.encryption={'sae' if radio.get('sae', True) else 'none'}",
            f"uci set wireless.{iface}.key=\"$MESH_KEY\"",
            "# batman-adv routes; 802.11s must only provide single-hop links.",
            f"uci set wireless.{iface}.mesh_fwding=0",
            f"uci set wireless.{iface}.mesh_rssi_threshold=0",
            f"uci set wireless.{iface}.mcast_rate={int(radio['multicast_rate_mbps']) * 1000}",
            f"uci set wireless.{iface}.network=bat_{b}",
            "",
            f"uci set network.bat_{b}=interface",
            f"uci set network.bat_{b}.proto=batadv_hardif",
            f"uci set network.bat_{b}.master=bat0",
            "# 1500 + 32 B batman-adv header, so bat0 itself keeps a 1500 B MTU",
            f"uci set network.bat_{b}.mtu={int(radio['mtu'])}",
        ]
    lines += [
        "",
        "# --- batman-adv ------------------------------------------------------------",
        "uci set network.bat0=interface",
        "uci set network.bat0.proto=batadv",
        f"uci set network.bat0.routing_algo={q(bat['algo'])}",
        f"# {bat['orig_interval_ms']} ms: worst-case reroute 3.0 s vs 5.7 s at 500 (sim_log step 18)",
        f"uci set network.bat0.orig_interval={int(bat['orig_interval_ms'])}",
        "uci set network.bat0.gw_mode=off",
        "uci set network.bat0.bridge_loop_avoidance=1",
        "uci set network.bat0.distributed_arp_table=1",
        "",
        "# --- LAN: host port + bat0 in one bridge, static, no DHCP/DNS --------------",
        "dev=$(uci -q show network | sed -n \"s/^network\\.\\([^.]*\\)\\.name='br-lan'$/\\1/p\" | head -n 1)",
        "uci -q del_list network.$dev.ports=bat0 || true",
        "uci add_list network.$dev.ports=bat0",
        "uci set network.lan.proto=static",
        f"uci set network.lan.ipaddr={router_ip(node, cfg)}",
        f"uci set network.lan.netmask={net.netmask}",
        "uci -q delete network.lan.gateway || true",
        "uci -q delete network.lan.dns || true",
        "uci -q delete network.lan.ip6assign || true",
        "# Every router bridges the same L2 segment: one DHCP server per router would",
        "# hand out conflicting leases across the mesh. Addresses are static instead.",
        "uci set dhcp.lan.ignore=1",
        "uci set dhcp.lan.dhcpv6=disabled",
        "uci set dhcp.lan.ra=disabled",
        "# The WAN port must never connect the fleet to campus networks.",
        "uci -q set network.wan.auto=0 || true",
        "uci -q set network.wan6.auto=0 || true",
        "",
        "# --- system ---------------------------------------------------------------",
        f"uci set system.@system[0].hostname={q('sortbots-' + node.name.replace('_', '-'))}",
        "# No internet on the mesh: time comes from the gateway's chrony on the hosts;",
        "# the router's own clock is only for its logs.",
        "uci -q set system.ntp.enabled=0 || true",
        "",
        "# 802.11b rates off (no uci option covers mesh mode on every release, so set",
        "# the rate mask each time a mesh interface comes up).",
        "mkdir -p /etc/hotplug.d/iface",
        "cat > /etc/hotplug.d/iface/99-sortbots-rates <<'HOTPLUG'",
        '[ "$ACTION" = ifup ] || exit 0',
        'case "$INTERFACE" in bat_g24) iw dev "$DEVICE" set bitrates legacy-2.4 ' + OFDM_RATES + ' ;; esac',
        "HOTPLUG",
        "",
        "uci commit",
        f"echo 'router-setup: {node.name} configured. Reboot, then from a host on the mesh:'",
        f"echo '  ssh root@{router_ip(node, cfg)} batctl n'",
    ]
    return "\n".join(lines) + "\n"


def netplan(node: F.Node, cfg: dict, iface: str) -> str:
    plen = ipaddress.ip_network(cfg["fleet"]["subnet"]).prefixlen
    return f"""# {node.name}: Ethernet port into its mesh router (commsim/hw/deploy.py).
# No gateway, no nameservers, no DHCP: the mesh is never a route to the
# internet, and nothing on it may depend on DHCP or DNS (plan §3).
network:
  version: 2
  ethernets:
    {iface}:
      dhcp4: false
      dhcp6: false
      accept-ra: false
      addresses: [{node.ip}/{plen}]
"""


def chrony(node: F.Node, fleet: list[F.Node], cfg: dict) -> str:
    gw = next(n for n in fleet if n.is_gateway)
    if node.is_gateway:
        return (f"# Gateway = fleet time source (plan §3); robots sync to it over the mesh.\n"
                f"allow {cfg['fleet']['subnet']}\n"
                "local stratum 8\n")
    return (f"# Sync to the gateway over the mesh. Latency numbers between hosts are\n"
            f"# only as good as this sync; `chronyc tracking` shows the offset.\n"
            f"server {gw.ip} iburst minpoll 2 maxpoll 4\n"
            "makestep 0.1 3\n")


def env_files(node: F.Node, fleet: list[F.Node], cfg: dict) -> tuple[str, str]:
    """router.env for rmw_zenohd, node.env for every ROS node on this host.
    Kept apart (as in emu/m1.py): one override in both would make each node
    try to listen on the router's mesh port."""
    router = (f"# source before `ros2 run rmw_zenoh_cpp rmw_zenohd` on {node.name}\n"
              "export RMW_IMPLEMENTATION=rmw_zenoh_cpp\n"
              f"export ZENOH_CONFIG_OVERRIDE={shlex.quote(F.zenoh_override(F.zenoh_router_config(node, fleet, cfg)))}\n")
    port = int(cfg["fleet"].get("zenoh_port", 7447))
    ov = ";".join([
        f'connect/endpoints=["tcp/127.0.0.1:{port}"]',
        'listen/endpoints=["tcp/127.0.0.1:0"]',
        "scouting/multicast/enabled=false",
        "transport/shared_memory/enabled=false",
    ])
    nodes = (f"# source before any ROS node on {node.name}: talk only to the local router\n"
             "export RMW_IMPLEMENTATION=rmw_zenoh_cpp\n"
             f"export ZENOH_CONFIG_OVERRIDE={shlex.quote(ov)}\n")
    return router, nodes


def apply_script(node: F.Node, iface: str) -> str:
    return f"""#!/usr/bin/env bash
# Apply {node.name}'s host network + time config. Run with sudo on that host.
set -euo pipefail
cd "$(dirname "$0")"
ip link show {iface} >/dev/null || {{ echo "no interface {iface}: set hardware.*_iface or --iface" >&2; exit 1; }}
install -m 600 netplan-sortbots-mesh.yaml /etc/netplan/60-sortbots-mesh.yaml
netplan apply
if [ -d /etc/chrony/conf.d ]; then
  install -m 644 chrony-sortbots.conf /etc/chrony/conf.d/sortbots.conf
  systemctl restart chrony
else
  echo "chrony not installed: apt install chrony, then rerun" >&2
fi
ip -br addr show {iface}
"""


def _must_be_private(out: Path) -> None:
    """The bundle holds the mesh key and the repo is public."""
    out = out.resolve()
    try:
        out.relative_to(REPO)
    except ValueError:
        return
    probe = out / "router-setup.sh"
    r = subprocess.run(["git", "-C", str(REPO), "check-ignore", "-q", str(probe)])
    if r.returncode != 0:
        raise SystemExit(f"{out} is inside the repo and not gitignored; the bundle holds the "
                         "mesh key. Use commsim/results/... or a path outside the repo.")


def read_key(path: Path, new: bool) -> str:
    path = path.expanduser()
    if new:
        if path.exists():
            raise SystemExit(f"{path} exists; refusing to overwrite the mesh key")
        path.parent.mkdir(parents=True, exist_ok=True)
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(secrets.token_urlsafe(24) + "\n")
    if not path.exists():
        raise SystemExit(f"no mesh key at {path} (create one with --new-key)")
    if path.stat().st_mode & 0o077:
        raise SystemExit(f"{path} is readable by others; chmod 600 it")
    key = path.read_text().strip()
    # SAE passphrase limits, and no quote characters so it survives uci + sh
    if not 8 <= len(key) <= 63 or any(c in key for c in "'\"\\$`\n"):
        raise SystemExit(f"{path}: key must be 8-63 chars with no quotes, $, ` or \\")
    return key


def deploy(cfg: dict, out: Path, key: str, sources: str,
           robot_iface: str | None = None, gateway_iface: str | None = None) -> list[F.Node]:
    fleet = F.generate(cfg, out)  # zenohd.json5, status_udp.json, cyclonedds.xml, fleet.json
    check_addresses(fleet, cfg)
    hw = cfg["hardware"]
    os.chmod(out, 0o700)
    for node in fleet:
        d = out / node.name
        os.chmod(d, 0o700)
        iface = (gateway_iface or hw["gateway_iface"]) if node.is_gateway else (robot_iface or hw["robot_iface"])
        router_env, node_env = env_files(node, fleet, cfg)
        files = {
            "router-setup.sh": router_script(node, fleet, cfg, key, sources),
            "netplan-sortbots-mesh.yaml": netplan(node, cfg, iface),
            "chrony-sortbots.conf": chrony(node, fleet, cfg),
            "router.env": router_env,
            "node.env": node_env,
            "apply-host.sh": apply_script(node, iface),
        }
        for name, text in files.items():
            (d / name).write_text(text)
            os.chmod(d / name, 0o700 if name.endswith(".sh") else 0o600)
    fl = json.loads((out / "fleet.json").read_text())
    for row, node in zip(fl, fleet):
        row["router_ip"] = router_ip(node, cfg)
    (out / "fleet.json").write_text(json.dumps(fl, indent=2) + "\n")
    return fleet


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("configs", nargs="+")
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--mesh-key-file", required=True, type=Path)
    ap.add_argument("--new-key", action="store_true", help="create the key file (refuses to overwrite)")
    ap.add_argument("--robot-iface", help="override hardware.robot_iface")
    ap.add_argument("--gateway-iface", help="override hardware.gateway_iface")
    a = ap.parse_args(argv)
    cfg = F.load_config(*a.configs)
    bad = check_timers(cfg)
    for v in bad:
        print(f"TIMER ORDER: {v}", file=sys.stderr)
    if bad:  # no override here: hardware never runs a config known to misfire
        return 2
    _must_be_private(a.out)
    key = read_key(a.mesh_key_file, a.new_key)
    a.out.mkdir(parents=True, exist_ok=True)
    sources = " + ".join(Path(c).name for c in a.configs)
    fleet = deploy(cfg, a.out, key, sources, a.robot_iface, a.gateway_iface)
    bad = F.check_dir(a.out, cfg["fleet"]["subnet"])
    for v in bad:
        print(f"VIOLATION {v}", file=sys.stderr)
    if bad:
        return 1
    for n in fleet:
        print(f"{n.name:10s} host {n.ip:15s} router {router_ip(n, cfg)}")
    print(f"bundles in {a.out} (contain the mesh key; don't commit or share them)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
